import Head from "next/head";
import styles from "../../styles/Home.module.css";
import stylesCustom from "../../styles/custom.module.css";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import React, { useState, useEffect, useRef } from "react";

import CryptoJS from "crypto-js";

import { FooterLogo } from "../../components/general";
import { Preferences } from "@capacitor/preferences";

//TODO : Atur Category Card agar kalau jumlah itemnya 6, bagus keliatanya
//TODO : Fit Screen No Scroll untuk pad dan Laptop

const VIBIO_SCRET_KEY = "jxUHlm9DKearBQ1";

export default function Evaluasi(props) {
  const [evaluasiURL, setEvaluasiURL] = useState("");
  const router = useRouter();
  const localeGeneral = props.localeData?.general;
  const pentunjuk_now = parseInt(router.query.petunjuk_number);

  useEffect(() => {
    Preferences.get({ key: "user_uuid" }).then((ret) => {
      let encryted_uuid = encodeURI(CryptoJS.AES.encrypt(ret.value, VIBIO_SCRET_KEY).toString().replace("/", "Por21Ld").replace("/", "Por21Ld"));
      console.log("https://elbicare.my.id/vibio_hidden/terapi-list/" + encodeURI(encryted_uuid))
      setEvaluasiURL("https://elbicare.my.id/vibio_hidden/terapi-list/" + encodeURI(encryted_uuid));
    });
  }, []);

  return (
    <div className={(styles.container, stylesCustom.backgound_image)} style={{ backgroundImage: "linear-gradient(rgba(36, 36, 36, 0.40), rgba(36, 36, 36, 0.40)), url('/bg.jpg')" }}>
      <Head>
        <title>Vibio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <motion.div
          className={styles.main}
          animate={"open"}
          variants={{
            open: { opacity: 1, x: 0 },
            closed: { opacity: 0, x: "-100%" },
          }}
        >
          <iframe src={evaluasiURL} style={{width: '100%', height: '100%'}}></iframe>
        </motion.div>
      </main>
      <div style={{ position: "absolute", top: "2vh", left: "2vh", cursor: "pointer" }} onClick={() => router.push("/home")}>
        <div className={stylesCustom.button_card}>
          <h4 style={{ marginBottom: "0px", color: "green" }}>Home</h4>
        </div>
      </div>
    </div>
  );
}

// export async function getStaticProps(context) {

//   return {
//     props: {
//       localeData: {
//         general: localeDataGeneral,
//       },
//     },
//   };
// }
