import Head from "next/head";
import Image from "next/legacy/image";
import styles from "../styles/Home.module.css";
import stylesCustom from "../styles/custom.module.css";
import { useRouter } from "next/router";
import { useAppContext } from "../context/state";
import React, { useState, useEffect, useRef } from "react";

import { Preferences } from "@capacitor/preferences";

import { getLocale } from "../utils/getLocaleText";
import { FooterLogo } from "../components/general";

import { ModalAnnaouncement } from "../components/modal";

export default function Home({ localeData }) {
  const router = useRouter();
  const { userdata, setUserdata } = useAppContext();
  const localeGeneral = localeData.general;
  const AudioSoundRef = useRef();
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    // if (navigator.mediaDevices.getUserMedia) {
    //   navigator.mediaDevices
    //     .getUserMedia({
    //       audio: true,
    //     })
    // } else {
    //   alert("Media Tidak tersedia");
    // }

    Preferences.get({ key: "user_uuid" }).then((ret) => {
      console.log(ret);
    });

    AudioSoundRef.current.play();
    Preferences.get({ key: "mainmenu_music" }).then((ret) => {
      if (ret.value == null) {
        AudioSoundRef.current.volume = parseInt(ret.value) / 100;
      }
    });
    console.log(userdata);
    setUserdata({
      username: "hola",
    });

    if (window.localStorage) {
      console.log(window.localStorage.getItem("userSession"));
      window.localStorage.setItem("userSession", "Loheee");
    }
  }, []);

  const closeModal = () => {
    setShowModal(false);
  };

  return (
    <div
      className={(styles.container, stylesCustom.backgound_image)}
      style={{ backgroundImage: "linear-gradient(rgba(36, 36, 36, 0.40), rgba(36, 36, 36, 0.40)), url('/bg2-uncom.jpg')" }}
    >
      <Head>
        <title>Vibio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          {/* <button type="button" className="btn btn-primary">Warning</button> */}
          <div className="d-flex align-items-center justify-content-center">
            <h1 className="display-2" style={{ color: "white", textShadow: "-2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000", textAlign: "center" }}>
              {localeGeneral.mainmenu_title}
            </h1>
          </div>
          <div className="d-flex align-items-center justify-content-center">
            <h4 className="display-8" style={{ color: "white", textShadow: "-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000", textAlign: "center" }}>
              {localeGeneral.mainmenu_subtitle}
            </h4>
          </div>
          <br></br>
          <div className="row">
            <div className="col-8 col-sm-8 col-md-6 mb-4 h-10 mx-auto">
              <div onClick={() => router.push("/demo")} className="card" style={{ textAlign: "center" }}>
                <h2 className={stylesCustom.card_menu_title_font}>{localeGeneral.menu1_title} &rarr;</h2>
                <p className={stylesCustom.card_menu_subtitle_font}>{localeGeneral.menu1_subtitle}</p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-8 col-sm-8 col-md-6 mb-4 h-10 mx-auto">
              <div onClick={() => router.push("/play")} className="card" style={{ textAlign: "center" }}>
                <h2 className={stylesCustom.card_menu_title_font}>{localeGeneral.menu2_title} &rarr;</h2>
                <p className={stylesCustom.card_menu_subtitle_font}>{localeGeneral.menu2_subtitle}</p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-8 col-sm-8 col-md-6 mb-4 h-10 mx-auto">
              <div onClick={() => router.push("/petunjuk-terapi/1")} className="card" style={{ textAlign: "center" }}>
                <h2 className={stylesCustom.card_menu_title_font}>{localeGeneral.menu3_title} &rarr;</h2>
                <p className={stylesCustom.card_menu_subtitle_font}>{localeGeneral.menu3_subtitle}</p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-8 col-sm-8 col-md-6 mb-4 h-10 mx-auto">
              <div onClick={() => router.push("/evaluasi")} className="card" style={{ textAlign: "center" }}>
                <h2 className={stylesCustom.card_menu_title_font}>{localeGeneral.menu4_title} &rarr;</h2>
                <p className={stylesCustom.card_menu_subtitle_font}>{localeGeneral.menu4_subtitle}</p>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-8 col-sm-8 col-md-6 mb-4 h-10 mx-auto">
              <FooterLogo></FooterLogo>
            </div>
          </div>
        </div>

        <ModalAnnaouncement isShow={showModal} clickFunction={closeModal}></ModalAnnaouncement>
      </main>
      <div className={stylesCustom.home_button} onClick={() => router.push("/pengaturan")}>
        <div className={stylesCustom.button_card}>
          <h4 style={{ marginBottom: "0px", color: "green" }}>S</h4>
        </div>
      </div>
      <audio ref={AudioSoundRef} controls loop autoPlay src={"/assets/music/bg-music1.wav"} style={{ display: "none" }}></audio>
    </div>
  );
}

export async function getStaticProps(context) {
  var localeDataGeneral = getLocale("id", "general");
  return {
    props: {
      localeData: {
        general: localeDataGeneral,
      },
    },
  };
}
