import Head from "next/head";
import styles from "../styles/Home.module.css";
import stylesCustom from "../styles/custom.module.css";
import { useRouter } from "next/router";
import { useAppContext } from "../context/state";
import { useEffect } from "react";

import { getLocale } from "../utils/getLocaleText";

export default function Home({ localeData }) {
  const router = useRouter();
  const { userdata, setUserdata } = useAppContext();
  const localeGeneral = localeData.general;

  useEffect(() => {
    console.log(userdata);
    setUserdata({
      username: "hola",
    });

    if (window.localStorage) {
      console.log(window.localStorage.getItem("userSession"));
      window.localStorage.setItem("userSession", "Loheee");
    }
  }, []);

  return (
    <div className={(styles.container, stylesCustom.backgound_image)} style={{ backgroundImage: "url('/bg2.jpg')" }}>
      <Head>
        <title>Vibio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        {/* <button type="button" className="btn btn-primary">Warning</button> */}
        <h1 className={styles.title}>{localeGeneral.mainmenu_title}</h1>
        <h3 className={styles.title}>{localeGeneral.mainmenu_subtitle}</h3>
        <br></br>
        <div className={stylesCustom.container_card_row}>
          <div href="#" className={stylesCustom.card_menu}>
            <h2>{localeGeneral.menu1_title} &rarr;</h2>
            <p>{localeGeneral.menu1_subtitle}</p>
          </div>

          <div onClick={() => router.push("/play")} className={stylesCustom.card_menu}>
            <h2>{localeGeneral.menu2_title} &rarr;</h2>
            <p>{localeGeneral.menu2_subtitle}</p>
          </div>

          <div href="#" className={stylesCustom.card_menu}>
            <h2>{localeGeneral.menu3_title} &rarr;</h2>
            <p>{localeGeneral.menu3_subtitle}</p>
          </div>

          <div href="#" className={stylesCustom.card_menu}>
            <h2>{localeGeneral.menu3_title} &rarr;</h2>
            <p>{localeGeneral.menu3_subtitle}</p>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}

export async function getStaticProps(context) {
  var localeDataGeneral = getLocale("id", "general");
  return {
    props: {
      localeData: {
        general: localeDataGeneral,
      },
    },
  };
}
