import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import stylesCustom from "../styles/custom.module.css";
import { useRouter } from "next/router";
import { useAppContext } from "../context/state";
import React, { useState, useEffect, useRef } from "react";

import { getLocale } from "../utils/getLocaleText";
import { FooterLogo } from "../components/general";

import { ModalAnnaouncement } from "../components/modal";

export default function Pengaturan({ localeData }) {
  const router = useRouter();
  const { userdata, setUserdata } = useAppContext();
  const localeGeneral = localeData.general;

  const inputServerRecog = useRef();
  const enableServerRecog = useRef();
  const [showModal, setShowModal] = useState(true);

  useEffect(() => {
    setUserdata({
      username: "hola",
    });

    if (window.localStorage) {
      console.log(window.localStorage.getItem("userSession"));
      window.localStorage.setItem("userSession", "Loheee");
      inputServerRecog.current.value = window.localStorage.getItem("recognitionServer");
      enableServerRecog.current.checked = (window.localStorage.getItem("enableRecog") == "true");
    }
  }, []);

  function savePengaturan() {
    window.localStorage.setItem("recognitionServer", inputServerRecog.current.value);
    window.localStorage.setItem("enableRecog", enableServerRecog.current.checked);
    router.push("/home")
    //
    //setGameType(type);
    //setPickGame(true);
  }

  return (
    <div className={(styles.container, stylesCustom.backgound_image)} style={{ backgroundImage: "url('/bg2-uncom.jpg')" }}>
      <Head>
        <title>Vibio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        {/* <button type="button" className="btn btn-primary">Warning</button> */}
        <h3 className={stylesCustom.menu_subtitle_font}>{localeGeneral.setting_title}</h3>
        <br></br>
        <div className={stylesCustom.container_card_row}>
          <div className={stylesCustom.card_menu_home_disabled} style={{ paddingBottom: "10px" }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
              <h2 className={stylesCustom.card_menu_title_font}>Enable Recog</h2>
              <input ref={enableServerRecog} type="checkbox" style={{ transform: "scale(3)" }} />
            </div>
          </div>
          <div className={stylesCustom.card_menu_home_disabled} style={{ paddingBottom: "10px" }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
              <h2 className={stylesCustom.card_menu_title_font}>Server Recognition</h2>
              <input type="text" ref={inputServerRecog} />
            </div>
          </div>
          <div className={stylesCustom.button_card} onClick={() => savePengaturan()}>
            <h4 style={{ marginBottom: "0px", color: "green" }}>Simpan</h4>
          </div>
        </div>
      </main>
      <audio controls loop autoPlay src={"/assets/music/bg-music1.wav"} style={{ display: "none" }}></audio>
      <div style={{ position: "absolute", top: "5vh", left: "5vh", cursor: "pointer" }} onClick={() => router.push("/home")}>
        <div className={stylesCustom.button_card}>
          <h4 style={{ marginBottom: "0px", color: "green" }}>Home</h4>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps(context) {
  var localeDataGeneral = getLocale("id", "general");
  return {
    props: {
      localeData: {
        general: localeDataGeneral,
      },
    },
  };
}
